### ISSUE TITLE
Integrated abstractions but no remote endpoint in menu

### ISSUE THREAD

**Issue by CFGrote** [askomics/flaskomics#251]
Hi,
I have uploaded and integrated the nextprot abstraction generated with
```
abstractor -s https://sparql.nextprot.org -o nextprot_abstraction.ttl
```
in my askomics instance. v4.3.0 . I was expecting to get an entry in the "Source" dropdown but "local" is still the only option. What am I doing wrong?

Thanks!

**Comment by mboudet** [comment]
Hello! I'll take a look.
Do you have the abstraction file available? (since it takes some time to generate a new one)

**Comment by CFGrote** [comment]
the file is here: https://gitlab.gwdg.de/c.fortmanngrote/sbw25_newgenome/-/raw/master/abstractions/nextprot_abstraction.ttl?inline=false

thanks!

**Comment by mboudet** [comment]
Thanks.

That's interesting, when using your file it does work in my instance.

![image](https://user-images.githubusercontent.com/17642511/122428781-83e61180-cf92-11eb-9d91-c7b70cecd1a8.png)

Do you perhaps use a custom internal askomics endpoint?
(IE, not http://askomics.org/internal)

**Comment by CFGrote** [comment]
that's a good hint. i'll check.


On Thu, 2021-06-17 at 08:38 -0700, mboudet wrote:
> Thanks.
> That's interesting, when using your file it does work in my instance.
> 
> Do you perhaps use a custom internal askomics endpoint?
> (IE, not http://askomics.org/internal)
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
-- 
Carsten Fortmann-Grote
Scientific Computing Services

Max-Planck-Institute for Evolutionary Biology
August-Thienemann-Strasse 2
24306 Plön
Germany

mail:  ***@***.***
phone: +49 (0)4522 763 277
web:   https://www.evolbio.mpg.de/scicomp

**Comment by CFGrote** [comment]
yes, that was it. i see the remote endpoint now.

can you explain to me the function of this variable in the askomics.env file? if i want to run my own internal askomics endpoint, would it be enough to change the prefix in the abstraction file accordingly?

**Comment by CFGrote** [comment]
another question, all local dataset integrations from before the change now stopped working. Any chance to bring them back without re-integrating them? some needed significant work on the header row.

**Comment by mboudet** [comment]
This variable sets the base uri for all askomics inner entities (like startPoint, etc). When Askomics tries to list the endpoints, it execute a sparql request [(this one i believe)](https://github.com/askomics/flaskomics/blob/0b52dd8faa0aa6d65eb923ada7c5655ac211ec1d/askomics/libaskomics/TriplestoreExplorer.py#L137). So it's going to be looking for entities with
```
?entity a askomics:entity .
?entity a askomics:startPoint.
```
With `askomics:` being a shortcut for the custom internal endpoint.
Since the base uri is mismatched, it's not going to find the entities.
(It's looking for http://askomics.org/yourinternaluri/entity, but in the file it's http://askomics.org/internal/entity)

(IRC, abstractor allows you to set --askomics-internal-namespace to specify your inner namespace)

For your second question, it should be fine to just change the first line of the ttl file to the actual inner namespace
(since all references after are based on this first line)

In case you want to revert back to the default namespace, there is a `make` command that will replace the current internal namespace in all graphs to a new one.

You'll need to call `make update-base-url` and specify the current and new internal namespace.
(You'll then need to call `make clear-cache` to reset cache abstraction)

Frabkly, I'd advise to just change the first line in the abstraction file and re-integrate it, it's less risky.

(I'd also advise to update to 4.3.1, since multiple categories selections are broken in 4.3)

**Comment by CFGrote** [comment]
thanks a lot for your detailed answer. i ended up reintegrating the "old" datasets, was less a hazzle than anticipated.
